x1: 60
x2: 280
key: 16
nbins: 3000
t0: 53
t1: 105
t2: 140
t3: 210
isDataList : [
              1,    2,   3,   4,    5,   6,     # A
              7,    8,   9,   10,   11,         # B
              12,  13,  14,   15,   16,           # C
              17,   18,                        # D
              19,20,
              21
              ]
              
modelName : "Aug28_3_20p01"
plotFolder : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/plots"
MCList_Z : [1, 3, 4, 19, 20, 21, 22]
MCList_H : [37, 36]
#MCList_H : [43, 36]
MCList_Z_sD: [45, 46, 47, 48, 49, 50, 51]
MCList_Z_sU: [57, 58, 59, 60, 61, 62, 63]
MCList_H_sD: [54, 53]
MCList_H_sU: [66, 65]
#MCList_H_sD: [55, 53]
#MCList_H_sU: [67, 65]
Bkg_params:
Bkg_params:
# F1
  1:
    B: 0.1165
    b: -23
    c: 0.6
    f: 0.22
    C: 11.7e-3
  0:
    xo: 60
    k: 1
    delta: -50
    beta: 3
  14:
    B: 0.1165
    b: -23
    c: 0.6
    f: 0.22
    aa: -6.58e-3
    bb: 11.7e-6
  16:
    x0: 37
    k: 0.078
    #p0_fall: -3.22e+3
    p1_fall: -0.0014699331848552339
    p0_rise: 0.85
    p1_rise: -0.005461024498886414
    p2_rise: 9.420935412026725e-06
  15:
    x0: 52
    A1: 1.5
    tau1: 1.81347154e+05
    A2: -1.447
    tau2: 1.63159252e+11
    tau3: 85




#F0
  
  
  
  


# Key 9
  #B: 0.1059341371681
  #b: -3.65627424979
  #c: 0.078558
  #mu_to: 43
  #sigma_to: 64
  #f: 0.36

Bkg_paramsLimits:
  #B: [0.0, 600]
  C: [0., 1]
  tau1: [0.000001, 1000]
  tau2: [0.000001, 1000]
  tau3: [0.000001, 1000]
  tau4: [0.000001, 1000]
  #mu_to: [35, 50]

output_file : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/hists/counts_cat2p0.root"
fitZSystematics : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/fit_parameters_with_systematics_Z.json"
fitHSystematics : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1/fit_parameters_with_systematics_H.json"