# config1.yaml
modelName: "Aug28_3_20p01"
outFolder: "/t3home/gcelotto/ggHbb/WSFit/output/cat11"
cuts_string: "(dijet_pt >= 100) & (PNN >= 0.79) & (PNN < 0.83) & ~((jet1_btagDeepFlavB >= 0.71) & (jet2_btagDeepFlavB >= 0.71))"

Z_MCList: [1, 3, 4,  19, 20, 21, 22]
Z_MCList_sD: [0]
Z_MCList_sU: [0]    # PLACEHOLDER
Z_x_bounds: [50, 140]
Z_nbins: 25
Z_fitFunction: "zPeak_dscb"
  

Z_params:
  fraction_dscb: 0.55
  mean: 95.61
  sigma: 12.6
  alphaL: 0.89
  nL: 1
  alphaR: 1.77
  nR: 1.1
  sigmaG: 12.9
Z_paramsLimits: 
  fraction_dscb: [0.05, 0.95]
  mean: [83, 97]
  nR: [1.1, 3]
  nL: [1.1, 10]
  sigma: [5, 15]
  sigmaG: [5, 15]


#Higgs params
H_MCList: [36,37]
H_MCList_sD: [1,3]
H_MCList_sU: [15,16]
H_x_bounds: [80, 160]
H_nbins: 20
H_fitFunction: "zPeak_dscb"
H_params:
  fraction_dscb: 0.15
  mean: 125.2
  alphaR: 1.69
  nR: 3.53
  alphaL: 1.69
  nL: 3.53
  sigma: 12
  sigmaG: 12.3
H_paramsLimits:
  fraction_dscb: [0,1]
  mean: [83,130]
  nR: [0.0000001, 100]
  alphaR: [0.0000001, 3]
  nL: [0.0000001, 100]
  alphaL: [0.0000001, 3]
  sigma: [0.1,20]
  sigmaG: [0.1,20]