x1: 65
x2: 220
nbins: 250 # These are edges number of bins will be nbins-1


t0: 50
t1: 105
t2: 140
t3: 200

key: 16
isDataList : [
              1,    2,   3,   4,    5,   6,     # A
              7,    8,   9,   10,   11,         # B
              12,  13,  14,   15,   16,           # C
              17,   18,                        # D
              19,20,
              21
              ]
modelName : "Aug28_3_20p01"
plotFolder : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1/plots"
MCList_Z : [1, 3, 4, 19, 20, 21, 22]
#MCList_H : [43, 36]
MCList_H : [37, 36]
MCList_Z_sD: [45, 46, 47, 48, 49, 50, 51]
MCList_Z_sU: [57, 58, 59, 60, 61, 62, 63]
MCList_H_sD: [54, 53]
MCList_H_sU: [66, 65]
#MCList_H_sD: [55, 53]
#MCList_H_sU: [67, 65]
Bkg_params:
# f0 parameters
  0:
    xo: 45
    k: 5
    beta: 16.e-3
    delta: -25
  1:
    B: 0.0605
    b: -20.66
    c: 0.37
    f: 0.034
    C: 8.7e-3
  16:
    x0: 60
    k: 0.09
    #p0_fall: -3.22e+3
    p1_fall: 1.98
    p0_rise: 91
    p1_rise: -0.66
    p2_rise: 0.00134
  #aa:  -5.64126e-3
  #bb: 9.2e-6

# Gamma parameters
  #xo: 20
  #a: 2 
  #scale: 10

  

Bkg_paramsLimits:
  #xo: [0,80]

# F0 limits
  xo: [0, 60]
  #k: [1, 100]
  beta: [1.e-4, 1.e-1]
#F16 limits
  x0: [0, 70]
  k: [0, 1]
  #k : [0.001,0.2]

# old parameters
  #B: [0, 0.1]


 
output_file : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1/hists/counts_cat2p1.root"
fitZSystematics : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1/fit_parameters_with_systematics_Z.json"
fitHSystematics : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1/fit_parameters_with_systematics_H.json"
