
modelName: "Mar31_9_200p0"
outFolder: "/t3home/gcelotto/ggHbb/WSFit/output/cat11"
cuts_string: "(PNN >= 0.74) & (PNN < 0.76)
              " 

Z_MCList: [1,  19, 20, 21, 22, 35]
#Higgs params
H_MCList: [37,36,48,49,50,51,52,53,54]