x1: 42
x2: 190
key: 7
nbins: 100
t0: 48
t1: 105
t2: 140
t3: 180
isDataList : [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18
              ]
              
modelName : "Mar21_2_0p0"
ptCut_min : 160
ptCut_max : null
jet1_btagMin : 0.71
jet2_btagMin : 0.71
PNN_t : 0.328
PNN_t_max : 0.75
plotFolder : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/plots"
MCList_Z : [1, 3, 4, 19, 20, 21, 22]
MCList_H : [37, 36]
#MCList_H : [43, 36]
MCList_Z_sD: [45, 46, 47, 48, 49, 50, 51]
MCList_Z_sU: [57, 58, 59, 60, 61, 62, 63]
MCList_H_sD: [54, 53]
MCList_H_sU: [66, 65]
#MCList_H_sD: [55, 53]
#MCList_H_sU: [67, 65]
params:
#Key 7
  B: 0.097
  C: 0.133
  b: -23.20820917885504 
  c: 0.4916871166283112

  aa: -0.008386020560364088
  bb: 1.9243766889046934e-05
  f: 0.16753801474327192 

# Key 9
  #B: 0.1059341371681
  #b: -3.65627424979
  #c: 0.078558
  #mu_to: 43
  #sigma_to: 64
  #f: 0.36

paramsLimits:
  B: [0.0, 10]
  C: [0., 1]
  #mu_to: [35, 50]

output_file : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/hists/counts_cat2p0.root"
fitZSystematics : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/fit_parameters_with_systematics.json"
