x1: 40
x2: 300
key: 7
nbins: 100
t0: 60
t1: 110
t2: 140
t3: 250
isDataList : [1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18
              ]
modelName : "Mar21_2_0p0"
ptCut_min : 160
ptCut_max : null
jet1_btagMin : 0.71
jet2_btagMin : 0.71
PNN_t : 0.328
PNN_t_max : 0.75
plotFolder : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/plots"
MCList_Z : [1, 3, 4, 19, 20, 21, 22]
MCList_H : [43, 36]
MCList_Z_sD: [45, 46, 47, 48, 49, 50, 51]
MCList_Z_sU: [57, 58, 59, 60, 61, 62, 63]
MCList_H_sD: [55, 53]
MCList_H_sU: [67, 65]
params:
  B: 0.24
  C: 0.066
  b: -37
  c: 0.6
  aa: -4.99e-3
  bb: 6.9e-6
  f: 0.05

paramsLimits:
  B: [0.0, 10]
  C: [0., 1]

output_file : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/hists/counts_cat2p0.root"
fitZSystematics : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0/fit_parameters_with_systematics.json"
