# config1.yaml
MCList: [1, 3, 4,  19, 20, 21, 22]
MCList_sD: [45, 46, 47, 48, 49, 50, 51]
MCList_sU: [57, 58, 59, 60, 61, 62, 63]
x_bounds: [60, 150]
modelName: "Mar21_2_0p0"
outFolder: "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p0"
fitFunction: "zPeak_dscb"
nbins: 80
cuts_dict:
  dijet_pt: [160, null]
  PNN: [0.328, 75]

params:
  fraction_dscb: 0.55
  mean: 92.61
  sigma: 10.6
  alphaL: 0.89
  nL: 1
  alphaR: 1.77
  nR: 0.58
  sigmaG: 10.9
paramsLimits: 
  fraction_dscb: [0.05, 0.95]
  mean: [83, 97]
  nR: [0.000001, 3]
  nL: [0.000001, 10]
  sigma: [5, 15]
  sigmaG: [5, 15]