#combine -M GenerateOnly -d datacardMulti10.txt --freezeParameters pdfindex_10_2016_13TeV,rateZbb --setParameters pdfindex_10_2016_13TeV=3 -t -1 --expectSignal 1

# Envelope
#combine -M MultiDimFit -d datacardMulti10.txt --toysFile higgsCombineTest.GenerateOnly.mH120.root --algo grid --setParameterRanges r=-4,9 --points 100 --cminDefaultMinimizerStrategy 0 --saveNLL -n Envelope -m 125  --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 --X-rtd MINIMIZER_freezeDisassociatedParams --expectSignal 1 --freezeParameters rateZbb
# PDFS
#combine -M MultiDimFit -d datacardMulti10.txt --toysFile higgsCombineTest.GenerateOnly.mH120.root --algo grid --setParameterRanges r=-4,9 --points 100 --cminDefaultMinimizerStrategy 0 --saveNLL -n fixed_pdf_0 -m 125 --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 --X-rtd MINIMIZER_freezeDisassociatedParams --expectSignal 1 --freezeParameters pdfindex_10_2016_13TeV,rateZbb --setParameters pdfindex_10_2016_13TeV=0 
#combine -M MultiDimFit -d datacardMulti10.txt --toysFile higgsCombineTest.GenerateOnly.mH120.root --algo grid --setParameterRanges r=-4,9 --points 100 --cminDefaultMinimizerStrategy 0 --saveNLL -n fixed_pdf_1 -m 125 --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 --X-rtd MINIMIZER_freezeDisassociatedParams --expectSignal 1 --freezeParameters pdfindex_10_2016_13TeV,rateZbb --setParameters pdfindex_10_2016_13TeV=1 
#combine -M MultiDimFit -d datacardMulti10.txt --toysFile higgsCombineTest.GenerateOnly.mH120.root --algo grid --setParameterRanges r=-4,9 --points 100 --cminDefaultMinimizerStrategy 0 --saveNLL -n fixed_pdf_2 -m 125 --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 --X-rtd MINIMIZER_freezeDisassociatedParams --expectSignal 1 --freezeParameters pdfindex_10_2016_13TeV,rateZbb --setParameters pdfindex_10_2016_13TeV=2 
#combine -M MultiDimFit -d datacardMulti10.txt --toysFile higgsCombineTest.GenerateOnly.mH120.root --algo grid --setParameterRanges r=-4,9 --points 100 --cminDefaultMinimizerStrategy 0 --saveNLL -n fixed_pdf_3 -m 125 --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 --X-rtd MINIMIZER_freezeDisassociatedParams --expectSignal 1 --freezeParameters pdfindex_10_2016_13TeV,rateZbb --setParameters pdfindex_10_2016_13TeV=3 

combine -M MultiDimFit -d datacardMulti10.txt --algo grid --setParameterRanges r=-4,9 --points 100 --cminDefaultMinimizerStrategy 0 --saveNLL -n Envelope -m 125  --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 --X-rtd MINIMIZER_freezeDisassociatedParams --expectSignal 1 -t -1
