x1: 40
x2: 300
key: 2
nbins: 90
t0: 40
t1: 130
t2: 130
t3: 290
isDataList : [1,
              2,
              3,
              4,
              5,
              6,
              7
              ]
modelName : "Mar21_1_0p0"
ptCut_min : 100
ptCut_max : 160
jet1_btagMin : 0.71
jet2_btagMin : 0.71
PNN_t : 0.575
PNN_t_max : null
plotFolder : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat1/plots"
MCList_Z : [1, 3, 4, 19, 20, 21, 22]
MCList_H : [43, 36]
params:
  B: 0.02474
  #C: 0.5047
  b: -0.01403
  c: 0.0001172

paramsLimits:
  B: [0.0, 0.05]
  #C: [0.1, 1]

output_file : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat1/hists/counts_cat1.root"
fitZSystematics : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat1/fit_parameters_with_systematics.json"
