# config1.yaml
modelName: "Jul01_3_3p0"
outFolder: "/t3home/gcelotto/ggHbb/newFit/afterNN/cat1"
cuts_dict:
  dijet_pt: [160, null]
  PNN: [0.75, 1]
  jet1_btagDeepFlavB: [0.71, null]
  jet2_btagDeepFlavB: [0.71, null]
  


Z_MCList: [1, 3, 4,  19, 20, 21, 22]
Z_MCList_sD: [45, 46, 47, 48, 49, 50, 51]
Z_MCList_sU: [57, 58, 59, 60, 61, 62, 63]
Z_x_bounds: [55, 250]
Z_nbins: 70
Z_fitFunction: "zPeak_dscb"

#Z params
Z_params:
  fraction_dscb: 0.18
  mean: 98.2
  alphaR: 1.69
  nR: 1.1
  alphaL: 1.69
  nL: 1.1
  sigma: 8
  sigmaG: 9.3
Z_paramsLimits:
  fraction_dscb: [0,1]
  #fractionG: [0,1]
  mean: [83,110]
  nR: [0.000001, 10]
  alphaR: [0.0000001, 3]
  nL: [0.000001, 10]
  alphaL: [0.0000001, 3]
  sigma: [0.1,20]
  sigmaG: [0.1,20]
  #nL: [0.0000001, 10]
  #alphaL: [0.0000001, 2]


#Higgs params
H_MCList: [36,37]
H_MCList_sD: [1,3]
H_MCList_sU: [15,16]
H_x_bounds: [50, 180]
H_nbins: 70
H_fitFunction: "zPeak_dscb"
H_params:
  fraction_dscb: 0.15
  mean: 125.2
  alphaR: 1.69
  nR: 3.53
  alphaL: 1.69
  nL: 3.53
  sigma: 8
  sigmaG: 9.3
H_paramsLimits:
  fraction_dscb: [0,1]
  mean: [83,130]
  nR: [0.0000001, 100]
  alphaR: [0.0000001, 3]
  nL: [0.0000001, 100]
  alphaL: [0.0000001, 3]
  sigma: [0.1,20]
  sigmaG: [0.1,20]