# config1.yaml
MCList: [1, 3, 4, 19,20, 21, 22]
x_bounds: [40, 300]
modelName: "Mar21_1_0p0"
outFolder: "/t3home/gcelotto/ggHbb/newFit/afterNN/cat1"
fitFunction: "zPeak_dscb"
nbins: 80
cuts_dict:
  dijet_pt: [100, 160]
  PNN: [0.575, null]


params:
  fraction_dscb: 0.55
  mean: 92.61
  sigma: 10.6
  alphaL: 0.89
  nL: 1
  alphaR: 1.77
  nR: 0.58
  sigmaG: 10.9
paramsLimits: 
  fraction_dscb: [0.05, 0.95]
  mean: [83, 97]
  nR: [0.000001, 3]
  nL: [0.000001, 10]
  sigma: [5, 15]
  sigmaG: [5, 15]