featuresForTraining:
  - jet1_pt_prime
  - jet1_eta_prime
  - jet1_btagWP
  - jet1_mass_prime

  - jet2_pt_prime
  - jet2_eta_prime
  - jet2_phi_prime
  - jet2_btagWP
  - jet2_mass_prime
  
  - jet3_pt_prime
  - jet3_eta_prime
  - jet3_phi_prime
  - jet3_btagWP
  - jet3_mass_prime

  - jet1_muon_pt_prime
  - jet1_muon_eta_prime
  - jet1_muon_phi_prime
  - jet1_muon_dxySig

  
  - dijet_pt_prime
  - dijet_eta_prime
  - dijet_phi_prime
  - dijet_mass
  - dijet_dR
  - dijet_dEta
  - dijet_twist
  - dijet_cs

  #- dimuon_mass
  #- cos_theta_star
  - dR_jet3_dijet
  - dPhi_jet3_dijet
  
  
  - nJets_20
  - nJets_30
  - nJets_50
  - ht_prime
  #- muon_dzSig
  #- leptonClass

# GEN INFORMATION
genFeatures:
  - jet1_muon_charge
  - b_gen_pt
  - b_gen_eta
  - b_gen_phi
  - b_gen_mass
  - antib_gen_pt
  - antib_gen_eta
  - antib_gen_phi
  - antib_gen_mass
  - higgs_gen_pt
  - higgs_gen_eta
  - higgs_gen_phi
  - higgs_gen_mass
  - dR_jet1_genQuark
  - dR_jet2_genQuark
  - dpT_jet1_genQuark
  - dpT_jet2_genQuark
  #- jet1_rest_pt
  #- jet2_rest_pt
  #- dimuon_mass
  - lambda2 
  #- jet1_sv_3dSig
  #- jet2_sv_3dSig
  - jet1_pt
  - jet1_eta
  - jet1_phi
  - jet1_leadTrackPt
  - jet1_mass
  - jet2_pt
  - jet2_eta
  - jet2_phi
  - jet2_leadTrackPt
  - jet2_mass
  - jet3_pt
  - jet3_eta
  - jet3_phi
  - jet3_leadTrackPt
  - jet3_mass
  - jet1_muon_pt
  - jet1_muon_eta
  - jet1_muon_phi
  - dijet_pt
  - dijet_eta
  - ht
  - normalized_dijet_pt


  - jet3_btagDeepFlavB
  - jet2_btagDeepFlavB
  - jet1_btagDeepFlavB
  - jet1_rest_eta
  - jet1_rest_phi
  - jet2_rest_eta
  - jet2_rest_phi

  #- dijet_pTAsymmetry
  #- centrality
  #- sphericity
  - jet1_phi_prime
  - jet1_sv_Ntrk
  - jet1_nConstituents
  - jet1_nTightMuons
  - jet1_nElectrons
  - jet2_sv_Ntrk
  - jet2_nConstituents
  - jet2_nTightMuons
  - jet2_nElectrons
  - jet3_nTightMuons
  - jet1_leadTrackPt_prime
  - jet2_leadTrackPt_prime
  - jet3_leadTrackPt_prime

  - dijet_phi
  - jet1_muon_pfRelIso03_all
  - flat_weight

mass_spin0:
  - 50
  - 70
  - 100
  - 200
  - 300


cuts:
  default:
    - "dijet_pt >= 100 & dijet_mass >= 50 & dijet_mass < 300"
  M50:
    - "higgs_gen_mass < 140 & dR_jet1_genQuark < 0.4 & dR_jet2_genQuark < 0.4"
  M70:
    - "higgs_gen_mass < 140 & dR_jet1_genQuark < 0.4 & dR_jet2_genQuark < 0.4"
  M100:
    - "higgs_gen_mass < 140 & dR_jet1_genQuark < 0.4 & dR_jet2_genQuark < 0.4"
  M125:
    - "dR_jet1_genQuark < 0.4 & dR_jet2_genQuark < 0.4"
  M200:
    - "dR_jet1_genQuark < 0.4 & dR_jet2_genQuark < 0.4"
  M300:
    - "dR_jet1_genQuark < 0.4 & dR_jet2_genQuark < 0.4"

# & dR_jet1_genQuark < 0.4 & dR_jet2_genQuark < 0.4"
