modelName: Apr01_1000p0
doubleDisco: true
x1: PNN1
x2: PNN2
xx: dijet_mass
t1: 0.25
t2: 0.3
isMCList: [0, 1, 3, 4, 19, 20, 21, 22, 35, 36]
isDataList: [0, 1, 2, 3, 4, 5, 6, 7]
detail: "7"
variations : [
    'Nominal',
    #'btag_Up', 'btag_Down',
    #'JECAbsoluteMPFBias_Up', 'JECAbsoluteMPFBias_Down','JECAbsoluteScale_Up', 'JECAbsoluteScale_Down','JECAbsoluteStat_Up', 'JECAbsoluteStat_Down','JECFlavorQCD_Up', 'JECFlavorQCD_Down','JECFragmentation_Up', 'JECFragmentation_Down','JECPileUpDataMC_Up', 'JECPileUpDataMC_Down','JECPileUpPtBB_Up', 'JECPileUpPtBB_Down','JECPileUpPtEC1_Up', 'JECPileUpPtEC1_Down','JECPileUpPtEC2_Up', 'JECPileUpPtEC2_Down','JECPileUpPtHF_Up', 'JECPileUpPtHF_Down','JECPileUpPtRef_Up', 'JECPileUpPtRef_Down','JECRelativeBal_Up', 'JECRelativeBal_Down','JECRelativeFSR_Up', 'JECRelativeFSR_Down','JECRelativeJEREC1_Up', 'JECRelativeJEREC1_Down','JECRelativeJEREC2_Up', 'JECRelativeJEREC2_Down','JECRelativeJERHF_Up', 'JECRelativeJERHF_Down','JECRelativePtBB_Up', 'JECRelativePtBB_Down','JECRelativePtEC1_Up', 'JECRelativePtEC1_Down','JECRelativePtEC2_Up', 'JECRelativePtEC2_Down','JECRelativePtHF_Up', 'JECRelativePtHF_Down','JECRelativeSample_Up', 'JECRelativeSample_Down','JECRelativeStatEC_Up', 'JECRelativeStatEC_Down','JECRelativeStatFSR_Up', 'JECRelativeStatFSR_Down','JECRelativeStatHF_Up', 'JECRelativeStatHF_Down','JECSinglePionECAL_Up', 'JECSinglePionECAL_Down','JECSinglePionHCAL_Up', 'JECSinglePionHCAL_Down','JECTimePtEta_Up', 'JECTimePtEta_Down',
]