x1: 45
x2: 300
nbins: 50


t0: 50
t1: 80
t2: 115
t3: 300

key: 9
isDataList : [
              1,
              2,
              3,
              4,
              5,
              6,
              7
              ]
modelName : "Mar21_2_0p0"
ptCut_min : 100
ptCut_max : null
jet1_btagMin : 0.71
jet2_btagMin : 0.71
PNN_t : 0.75
PNN_t_max : null
plotFolder : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1/plots"
MCList_Z : [1, 3, 4, 19, 20, 21, 22]
MCList_H : [43, 36]
params:
  B: 0.009
  #C: 0.006
  b: 0.18
  c: 0.001
  #aa: 0.01
  #bb: -0.0001
  f: 0.75
  #m0: 30
  #p2: 100
  mu_to: 70
  sigma_to: 25
  #f: 0.5
  #C: 0.5047
  #cc: 0
paramsLimits:
  B: [0.0, 0.05]
  f: [0., 1]
  sigma_to: [0,20]

  #C: [0.1, 1]

output_file : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1/hists/counts_cat2p1.root"
fitZSystematics : "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1/fit_parameters_with_systematics.json"
