# config1.yaml
modelName: "Aug28_3_20p01"
outFolder: "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1"
cuts_dict:
  dijet_pt: [100, null]
  PNN: [0.7, null]
  jet1_btagDeepFlavB: [0.71, null]
  jet2_btagDeepFlavB: [0.71, null]
  

# Z Params
Z_MCList: [1, 3, 4,  19, 20, 21, 22]
Z_MCList_sD: [0]
Z_MCList_sU: [0]
Z_x_bounds: [55, 150]
Z_nbins: 70
Z_fitFunction: "zPeak_dscb"
Z_params:
  fraction_dscb: 0.18
  mean: 98.2
  alphaR: 1.69
  nR: 3.53
  alphaL: 1.69
  nL: 3.53
  sigma: 8
  sigmaG: 9.3
Z_paramsLimits:
  fraction_dscb: [0,1]
  mean: [83,110]
  nR: [1.00001, 10]
  alphaR: [0.0000001, 3]
  nL: [1.0001, 10]
  alphaL: [0.0000001, 3]
  sigma: [6,15]
  sigmaG: [6,15]

#Higgs params
H_MCList: [36,37]
H_MCList_sD: [1,3]
H_MCList_sU: [15,16]
H_x_bounds: [50, 170]
H_nbins: 40
H_fitFunction: "zPeak_dscb"
H_params:
  fraction_dscb: 0.15
  mean: 125.2
  alphaR: 1.69
  nR: 3.53
  alphaL: 1.69
  nL: 3.53
  sigma: 8
  sigmaG: 9.3
H_paramsLimits:
  normSig_H: [0,null]
  fraction_dscb: [0,1]
  mean: [110,130]
  nR: [1., 10]
  alphaR: [0.0000001, 3]
  nL: [1.00001, 10]
  alphaL: [0.0000001, 3]
  sigma: [0.1,20]
  sigmaG: [0.1,20]