# config1.yaml
MCList: [1, 3, 4,  19, 20, 21, 22]
MCList_sD: [45, 46, 47, 48, 49, 50, 51]
MCList_sU: [57, 58, 59, 60, 61, 62, 63]
x_bounds: [55, 150]
nbins: 70
modelName: "Mar21_2_0p0"
outFolder: "/t3home/gcelotto/ggHbb/newFit/afterNN/cat2/cat2p1"
fitFunction: "zPeak_dscb"
cuts_dict:
  dijet_pt: [160, null]
  PNN: [0.75, null]


params:
  fraction_dscb: 0.18
  mean: 98.2
  alphaR: 1.69
  nR: 3.53
  alphaL: 1.69
  nL: 3.53
  sigma: 8
  sigmaG: 9.3
paramsLimits:
  fraction_dscb: [0,1]
  #fractionG: [0,1]
  mean: [83,110]
  nR: [0.0000001, 100]
  alphaR: [0.0000001, 3]
  nL: [0.0000001, 100]
  alphaL: [0.0000001, 3]
  sigma: [0.1,20]
  sigmaG: [0.1,20]
  #nL: [0.0000001, 10]
  #alphaL: [0.0000001, 2]